version: '3.1'
services:
  adminer:
      image: dockette/adminer:full-php5
      restart: always
      ports:
          - 8080:8080
  dbPostgres:
      image: postgres:10
      restart: always
      ports:
          - 5432:5432
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: test
          POSTGRES_DB: ${POSTGRES_DATABASE}