version: "3"

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./backend/data/pg:/var/lib/postgresql/data
    entrypoint : ["bash","-c", "echo '' > /var/lib/postgresql/data/.keep && rm /var/lib/postgresql/data/.keep && docker-entrypoint.sh postgres"]
    ports:
      - ${DB_PORT}:5432
    networks:
      - infinity_network
    restart: always
  
  adminer:
    image: adminer:4
    container_name: adminer
    ports:
      - ${ADMINER_PORT}:8080
    restart: always
    networks:
      - infinity_network

networks:
  infinity_network:
    name: "infinity_network"

