version: "3"

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./backend/data/pg:/var/lib/postgresql/data
    entrypoint : ["bash","-c", "echo '' > /var/lib/postgresql/data/.keep && rm /var/lib/postgresql/data/.keep && docker-entrypoint.sh postgres"]
    ports:
      - ${DB_PORT}:5432
    networks:
      - infinity_network
    restart: always

  adminer:
    image: adminer:4
    container_name: adminer
    ports:
      - ${ADMINER_PORT}:8080
    restart: always
    networks:
      - infinity_network

# volumes:
#   pgdata:
#     name: "pgdata"
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "${DB_DATA}"

networks:
  infinity_network:
    name: "infinity_network"

# version: '3'

# services:
#   postgres:
#     container_name: postgres
#     build: ./backend/
#     image: postgres:latest
#     ports:
#       - "5432:5432"
#     env_file:
#       - docker.env
#     volumes:
#       - ./backend/data/db:/var/lib/postgresql/data
#     networks:
#       - postgres
    
#   pgadmin:
#     links:
#     - postgres:postgres
#     container_name: pgadmin
#     image: dpage/pgadmin4
#     ports:
#     - "8080:80"
#     volumes:
#     - ./backend/data/admin:/root/.pgadmin
#     env_file:
#     - docker.env
#     networks:
#     - postgres

# volumes:
#   postgres:
#     driver: local

# networks:
#   postgres:
#     driver: bridge

# version: "3"
# services:
#   postgres:
#     container_name: postgres
#     image: postgres:latest
#     ports:
#     - "5432:5432"
#     volumes:
#     - /Users/mlecherb/Common-Core/ft_transcendence/backend/data/postgres:/var/lib/postgresql/data
#     env_file:
#     - docker.env
#     networks:
#     - postgres
 
#   pgadmin:
#     links:
#     - postgres:postgres
#     container_name: pgadmin
#     image: dpage/pgadmin4
#     ports:
#     - "8080:80"
#     volumes:
#     - /Users/mlecherb/Common-Core/ft_transcendence/backend/data/pgadmin:/root/.pgadmin
#     env_file:
#     - docker.env
#     networks:
#     - postgres
 
# networks:
#   postgres:
#     driver: bridge
