version: '3.7'

services:
  nestjs:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
        - ./backend:/app/
    ports:
        - 4200:4200

  svelte:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/test-app/
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./backend/data/pg:/var/lib/postgresql/data
    entrypoint:
      [
        "bash",
        "-c",
        "echo '' > /var/lib/postgresql/data/.keep && rm /var/lib/postgresql/data/.keep && docker-entrypoint.sh postgres"
      ]
    ports:
      - ${DB_PORT}:5432
    restart: always

  adminer:
    image: adminer:4
    container_name: adminer
    ports:
      - ${ADMINER_PORT}:8080
    restart: always
